---
deployment:
  tasks:
    - /bin/cp -a build/web/* /home/ghst2026/public_html/ || true
    - /bin/cp -a build/web/.htaccess /home/ghst2026/public_html/.htaccess || true
    - /bin/cp -a api /home/ghst2026/public_html/ || true
